### ISSUE TITLE
Detached progress bar bug

### ISSUE THREAD

**Issue by beastie1** [Emdek/otter#358] opened 2014-06-15 11:24 UTC
Hello.

Like the title says and the screenshot below shows, the progress bar sometimes appears well above the tab bar on the top of which it is usually attached.

![screenshot_26052014-134643](https://cloud.githubusercontent.com/assets/6757832/3280805/27a84208-f47f-11e3-8991-6058f342800d.jpg)

**Comment by Emdek** [comment] 2015-01-01 09:11
Apparently #587 was a duplicate of this ticket.

**Closed by Emdek** 2015-01-01 09:11 UTC
Labels: bug, component: GUI, component: QtWebKitBackend, severity: low priority
