### ISSUE TITLE
Make Tabs Have Rounded Corners

### ISSUE THREAD

**Issue by opticyclic** [Emdek/otter#666] opened 2015-01-21 03:34 UTC
The tabs on Opera 12.17 have rounded corners but the tabs in Otter have very sharp corners.

**Comment by Emdek** [comment] 2015-01-21 16:21
It's up to theme, currently we are using native style, but we plan to add support for Opera themes, so it makes it duplicate of #36.

**Closed by Emdek** 2015-01-21 16:21 UTC
Labels: duplicate

**Comment by opticyclic** [comment] 2015-01-23 23:51
If you are using native style, why are the default bookmark icons KDE blue and not Windows yellow?

**Comment by Emdek** [comment] 2015-01-26 00:53
@opticyclic, icons are not part of theme, although in this specific case we could try to use `QStyle::SP_DirIcon` (one of standard pixmaps).

See also:
http://doc-snapshot.qt-project.org/qt5-5.4/qicon.html#fromTheme
