### ISSUE TITLE
Dynamic menus concept

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#684] opened 2015-02-01 09:39 UTC
In old Opera there was, prior to speed dial, a Top 10 menu. In browsers like Chrome and FF this has moved into the speed dial. In Chrome and FF you see your most visited sites in the speed dial, unless you fix the items there later, whereas in Opera you saw the most visited sites in a Top 10 menu. 

I personally do not care for the Top 10 menu, but I care for similar menus that Opera had, such as 

- Tabs menu (for open tabs, similar to Closed tabs menu)
- Panels menu (useful as an alternative to Panels toolbar, which is currently lost)
- Feeds menu
- Sessions menu, etc.

In Opera INI files, these were often called lists, like Internal Popular List, Internal Window List, Internal Closed Window List, etc. It would make sense to make these lists available for users as actions so they could be put anywhere. For example some people would like to see the list of open tabs in a menu in the menu bar, not as a tabbar.

**Comment by Emdek** [comment] 2015-02-01 09:42
Duplicate of #65.
Maybe not all details were exposed properly in that ticket it's intention is to have exactly something like this, but using different storage format.

**Closed by Emdek** 2015-02-01 09:42 UTC
Labels: duplicate
