### ISSUE TITLE
Login dialogue keeps popping up on Sharepoint site

### ISSUE THREAD

**Issue by Stullemon** [Emdek/otter#659] opened 2015-01-14 07:01 UTC
I am using Otter (weekly 54) to connect to a Sharepoint-based project-internal collaboration site which is used strictly for document sharing. After I log in I can browse the site but on practically any click the login dialogue ("Authentication Required") pops up again. Just cancelling it allows me to keep on browsing. Still, it is sort of inconvenient to have to cancel the dialogue all the time.

Can I help you debugging this issue?

**Comment by Emdek** [comment] 2015-01-19 21:05
Looks like a duplicate of #509, or at least close enough to be solved using the same solution.

**Closed by Emdek** 2015-01-19 21:05 UTC
Labels: duplicate
