### ISSUE TITLE
Print Preview Crashes On GitHub

### ISSUE THREAD

**Issue by opticyclic** [Emdek/otter#668] opened 2015-01-21 03:46 UTC
Print Preview causes Otter to crash on GitHub pages e.g. https://github.com/Emdek/otter but works fine for some other pages e.g. http://www.google.com

**Comment by The-Compiler** [comment] 2015-01-21 05:19
I also noticed this in https://github.com/The-Compiler/qutebrowser/issues/326 - it seems to be the same issue as reported here: https://bugreports.qt.io/browse/QTBUG-43322

You're also on Windows I guess?

**Comment by resbro** [comment] 2015-01-21 16:17
Issue 497?

Yeah windows

**Comment by Emdek** [comment] 2015-01-21 16:19
@resbro, yeah, looks like duplicate of #497.

**Closed by Emdek** 2015-01-21 16:19 UTC
Labels: duplicate
