### ISSUE TITLE
Personal bar with bookmarks and folders

### ISSUE THREAD

**Issue by vapaamies** [Emdek/otter#688] opened 2015-02-02 09:13 UTC
Just like on the screenshot. It's from my home machine, these bookmarks are *not so many*. On the work, there are 3-5 folders on the panel, one folder per using technology or server. Personal bar folders are too handy because they need only two clicks to use.

![Bookmark folder](http://vivaldi.net/media/kunena/attachments/14266/UserMenu-Docs.png)

**Comment by Emdek** [comment] 2015-02-02 15:29
Duplicate of #31.
I'm going for roles for toolbars, so new toolbar with *bookmarks* set as role would show contents of selected folder (root or subfolder) while allowing for multiple toolbars with different folders set (as only few toolbars will be "special", like navigation, tab bar etc.).

**Closed by Emdek** 2015-02-02 15:29 UTC
Labels: duplicate
