### ISSUE TITLE
add more mouse gestures

### ISSUE THREAD

**Issue by codespotx** [Emdek/otter#687] opened 2015-02-01 11:32 UTC
in opera "down" gesture above link opens link in new window, otter does nothing.

there might be some other missing gestures, but this one I actually used ;-)

full list (see "link gesture"):
http://help.opera.com/Windows/12.10/en/gestures.html

**Comment by Emdek** [comment] 2015-02-01 11:35
Duplicate of #633 (well, not really obvious, granted).

**Closed by Emdek** 2015-02-01 11:35 UTC
Labels: duplicate
