### ISSUE TITLE
Copy link text

### ISSUE THREAD

**Issue by ersi-dnd** [Emdek/otter#640] opened 2015-01-03 10:39 UTC
Copy url is a normal function in every browser, but there's an additional thing that I need routinely in my work. The difference is this:

    <a href="url is here">link text is here</a> 

There's a FF extension that copies the text between the anchors rather than the url. This function was in some way present in Opera's Links manager too, but I found no way to put it conveniently into the immediate menus where I wanted. Anyway, in Opera it didn't matter much because in Presto you could easily select link texts from anywhere with mouse, partially or entirely. 

A separate action to copy link text is now important with webkit, because in webkit it's not easy to select link texts. Just try to begin selecting from the middle of a link text with mouse. Not working in webkit browsers, while it works fine in Opera.

Perhaps it would even make sense to be able to copy separately the link title?

    <a href="url is here" title="title is here">link text is here</a>

...which is usually displayed as the tooltip in browsers, so browsers evidently do something with it, so why should they not do more with it? And similarly with whatever else can be put into the anchor tags. The same idea applies to wherever else some title or alt content may be present, such as in img and abbr tags.

Additionally it would be nice to have a way to Extract the link text (and title and alt content) rather than Copy to clipboard, for example to lift it to the secondary address field without going via clipboard, as described in #639. 

This perhaps also gives you ideas about the functionality of Links manager, which should be one of the big things for the sidebar and about:pages.

**Comment by Emdek** [comment] 2015-01-03 16:02
> Perhaps it would even make sense to be able to copy separately the link title?
Definitely not, that would be one step too far. ;-)
Each action has its cost (memory, additional string multiplied by amount of supported languages...), we can't afford to add such actions, it's a task for extensions.
Copying text of current link makes some sense, but it won't make much sense after implementing #111 or adding workaround for #109.

I'm considering this ticket as duplicate of #111, please continue discussion there.

**Closed by Emdek** 2015-01-03 16:02 UTC
Labels: duplicate
